"""全字段测试二轮

Revision ID: 32ca0c00c3b6
Revises: 21e6464401c0
Create Date: 2026-06-01 13:26:52.050540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ca0c00c3b6'
down_revision: Union[str, Sequence[str], None] = '21e6464401c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_demo_all_types', 'text_value',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='长文本-text')
    op.alter_column('module_demo_all_types', 'real_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_comment='单精度浮点-real',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_demo_all_types', 'real_value',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='单精度浮点-real',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'text_value',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='长文本-text')
    # ### end Alembic commands ###
