"""测试生成枚举

Revision ID: 53f8c7000baf
Revises: 89ef9e0a058d
Create Date: 2026-06-01 15:31:13.200786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f8c7000baf'
down_revision: Union[str, Sequence[str], None] = '89ef9e0a058d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TYPE "demo_status_enum" ADD VALUE IF NOT EXISTS \'TEST\'')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TYPE "demo_status_enum" RENAME TO "demo_status_enum_old"')
    op.execute('CREATE TYPE "demo_status_enum" AS ENUM (\'DRAFT\', \'ACTIVE\', \'DISABLED\')')
    op.execute('ALTER TABLE "public"."module_demo_all_types" ALTER COLUMN "enum_value" TYPE "demo_status_enum" USING "enum_value"::text::"demo_status_enum"')
    op.execute('DROP TYPE "demo_status_enum_old"')
    # ### end Alembic commands ###
