"""测试生成枚举

Revision ID: 7a7542d72b53
Revises: b8ee18e0a936
Create Date: 2026-06-01 20:21:24.274912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7542d72b53'
down_revision: Union[str, Sequence[str], None] = 'b8ee18e0a936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_demo_all_types', 'create_by',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'update_by',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'remark',
               existing_type=sa.VARCHAR(length=500),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'description',
               existing_type=sa.TEXT(),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'sort_no',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'del_flag',
               existing_type=sa.VARCHAR(length=1),
               comment='',
               existing_nullable=True)
    op.execute('CREATE TYPE "module_uuid_demo_type_enum" AS ENUM (\'normal\', \'important\', \'urgent\')')
    op.add_column('module_uuid_demo', sa.Column('type', sa.Enum('normal', 'important', 'urgent', name='module_uuid_demo_type_enum'), nullable=True, comment='业务类型'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_uuid_demo', 'type')
    op.execute('DROP TYPE IF EXISTS "module_uuid_demo_type_enum"')
    op.alter_column('module_demo_all_types', 'del_flag',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'sort_no',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'remark',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'update_by',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'create_by',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
