"""测试生成枚举

Revision ID: 7f451fa911ae
Revises: 7a7542d72b53
Create Date: 2026-06-01 21:13:57.274697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f451fa911ae'
down_revision: Union[str, Sequence[str], None] = '7a7542d72b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_demo_all_types', 'create_by',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'update_by',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'remark',
               existing_type=sa.VARCHAR(length=500),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'description',
               existing_type=sa.TEXT(),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'sort_no',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'del_flag',
               existing_type=sa.VARCHAR(length=1),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_demo_all_types', 'del_flag',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'sort_no',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'remark',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'update_by',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'create_by',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
