"""全字段测试二轮

Revision ID: a973c6a7285b
Revises: 32ca0c00c3b6
Create Date: 2026-06-01 13:40:50.756040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a973c6a7285b'
down_revision: Union[str, Sequence[str], None] = '32ca0c00c3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_demo_all_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID-bigint'),
    sa.Column('string_value', sa.String(length=100), nullable=False, comment='字符串-varchar'),
    sa.Column('fixed_char_value', sa.CHAR(length=1), nullable=True, comment='定长字符-char'),
    sa.Column('unicode_value', sa.Unicode(length=100), nullable=True, comment='Unicode字符串-unicode'),
    sa.Column('text_value', sa.Text(), nullable=True, comment='长文本-text'),
    sa.Column('unicode_text_value', sa.UnicodeText(), nullable=True, comment='Unicode长文本-unicode text'),
    sa.Column('small_integer_value', sa.SmallInteger(), nullable=True, comment='短整数-smallint'),
    sa.Column('integer_value', sa.Integer(), nullable=True, comment='整数-integer'),
    sa.Column('big_integer_value', sa.BigInteger(), nullable=True, comment='长整数-bigint'),
    sa.Column('numeric_value', sa.Numeric(precision=18, scale=6), nullable=True, comment='高精度小数-numeric'),
    sa.Column('decimal_value', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='高精度小数-decimal'),
    sa.Column('money_value', postgresql.MONEY(), nullable=True, comment='金额-money'),
    sa.Column('float_value', sa.Float(), nullable=True, comment='浮点数-float'),
    sa.Column('real_value', sa.REAL(), nullable=True, comment='单精度浮点-real'),
    sa.Column('double_value', sa.DOUBLE_PRECISION(), nullable=True, comment='双精度浮点-double precision'),
    sa.Column('boolean_value', sa.Boolean(), nullable=True, comment='布尔-boolean'),
    sa.Column('date_value', sa.Date(), nullable=True, comment='日期-date'),
    sa.Column('time_value', sa.Time(), nullable=True, comment='时间-time without time zone'),
    sa.Column('time_tz_value', sa.Time(timezone=True), nullable=True, comment='带时区时间-time with time zone'),
    sa.Column('datetime_value', sa.DateTime(), nullable=True, comment='日期时间-timestamp without time zone'),
    sa.Column('datetime_tz_value', sa.DateTime(timezone=True), nullable=True, comment='带时区日期时间-timestamp with time zone'),
    sa.Column('interval_value', sa.Interval(), nullable=True, comment='时间间隔-interval'),
    sa.Column('json_value', sa.JSON(), nullable=True, comment='JSON-json'),
    sa.Column('jsonb_object_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON对象-jsonb/object'),
    sa.Column('jsonb_array_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON数组-jsonb/array'),
    sa.Column('jsonpath_value', postgresql.JSONPATH(), nullable=True, comment='JSON路径-jsonpath'),
    sa.Column('binary_value', sa.LargeBinary(), nullable=True, comment='二进制-bytea'),
    sa.Column('enum_value', sa.Enum('DRAFT', 'ACTIVE', 'DISABLED', name='demo_status_enum'), nullable=True, comment='枚举-enum'),
    sa.Column('uuid_value', sa.UUID(), nullable=True, comment='UUID-uuid'),
    sa.Column('string_array_value', postgresql.ARRAY(sa.String(length=100)), nullable=True, comment='字符串数组-array/varchar'),
    sa.Column('integer_array_value', postgresql.ARRAY(sa.Integer()), nullable=True, comment='整数数组-array/integer'),
    sa.Column('jsonb_array_items_value', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True, comment='JSONB数组-array/jsonb'),
    sa.Column('inet_value', postgresql.INET(), nullable=True, comment='IP地址-inet'),
    sa.Column('cidr_value', postgresql.CIDR(), nullable=True, comment='网络地址-cidr'),
    sa.Column('macaddr_value', postgresql.MACADDR(), nullable=True, comment='MAC地址-macaddr'),
    sa.Column('macaddr8_value', postgresql.MACADDR8(), nullable=True, comment='EUI-64 MAC地址-macaddr8'),
    sa.Column('bit_value', postgresql.BIT(length=1), nullable=True, comment='固定长度位-bit'),
    sa.Column('bit_varying_value', postgresql.BIT(length=16, varying=True), nullable=True, comment='可变长度位-bit varying'),
    sa.Column('tsvector_value', postgresql.TSVECTOR(), nullable=True, comment='全文检索向量-tsvector'),
    sa.Column('tsquery_value', postgresql.TSQUERY(), nullable=True, comment='全文检索查询-tsquery'),
    sa.Column('int4_range_value', postgresql.INT4RANGE(), nullable=True, comment='整数范围-int4range'),
    sa.Column('int8_range_value', postgresql.INT8RANGE(), nullable=True, comment='长整数范围-int8range'),
    sa.Column('numeric_range_value', postgresql.NUMRANGE(), nullable=True, comment='小数范围-numrange'),
    sa.Column('date_range_value', postgresql.DATERANGE(), nullable=True, comment='日期范围-daterange'),
    sa.Column('timestamp_range_value', postgresql.TSRANGE(), nullable=True, comment='时间戳范围-tsrange'),
    sa.Column('timestamp_tz_range_value', postgresql.TSTZRANGE(), nullable=True, comment='带时区时间戳范围-tstzrange'),
    sa.Column('int4_multirange_value', postgresql.INT4MULTIRANGE(), nullable=True, comment='整数多范围-int4multirange'),
    sa.Column('int8_multirange_value', postgresql.INT8MULTIRANGE(), nullable=True, comment='长整数多范围-int8multirange'),
    sa.Column('numeric_multirange_value', postgresql.NUMMULTIRANGE(), nullable=True, comment='小数多范围-nummultirange'),
    sa.Column('date_multirange_value', postgresql.DATEMULTIRANGE(), nullable=True, comment='日期多范围-datemultirange'),
    sa.Column('timestamp_multirange_value', postgresql.TSMULTIRANGE(), nullable=True, comment='时间戳多范围-tsmultirange'),
    sa.Column('timestamp_tz_multirange_value', postgresql.TSTZMULTIRANGE(), nullable=True, comment='带时区时间戳多范围-tstzmultirange'),
    sa.Column('oid_value', postgresql.OID(), nullable=True, comment='对象ID-oid'),
    sa.Column('regclass_value', postgresql.REGCLASS(), nullable=True, comment='关系对象-regclass'),
    sa.Column('regconfig_value', postgresql.REGCONFIG(), nullable=True, comment='文本搜索配置-regconfig'),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_no', sa.Float(), nullable=True),
    sa.Column('del_flag', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Demo全类型测试表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_demo_all_types')
    # ### end Alembic commands ###
