"""测试生成枚举

Revision ID: b8ee18e0a936
Revises: ffa301fbd93e
Create Date: 2026-06-01 20:02:53.613112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8ee18e0a936'
down_revision: Union[str, Sequence[str], None] = 'ffa301fbd93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_uuid_demo',
    sa.Column('id', sa.Uuid(), nullable=False, comment='主键ID-uuid'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='业务标题'),
    sa.Column('business_code', sa.String(length=64), nullable=True, comment='业务编号'),
    sa.Column('customer_name', sa.String(length=100), nullable=True, comment='客户名称'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='业务状态'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='优先级'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='业务金额'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('occurred_date', sa.Date(), nullable=True, comment='发生日期'),
    sa.Column('closed_time', sa.DateTime(), nullable=True, comment='关闭时间'),
    sa.Column('extra_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展信息'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('sort_no', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('del_flag', sa.String(length=1), nullable=True, comment='删除标志'),
    sa.PrimaryKeyConstraint('id'),
    comment='UUID主键业务示例表'
    )
    op.alter_column('module_demo_all_types', 'create_by',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'update_by',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'remark',
               existing_type=sa.VARCHAR(length=500),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'description',
               existing_type=sa.TEXT(),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'sort_no',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'del_flag',
               existing_type=sa.VARCHAR(length=1),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_demo_all_types', 'del_flag',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'sort_no',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'remark',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'update_by',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'create_by',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_table('module_uuid_demo')
    # ### end Alembic commands ###
