"""jsonschema

Revision ID: c5a30dfe05b6
Revises: 7f451fa911ae
Create Date: 2026-06-02 23:39:43.330675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5a30dfe05b6'
down_revision: Union[str, Sequence[str], None] = '7f451fa911ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_model_refs',
    sa.Column('ref_id', sa.String(length=64), nullable=False, comment='引用ID'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型ID'),
    sa.Column('ref_model_id', sa.String(length=64), nullable=False, comment='被引用模型ID'),
    sa.Column('ref_path', sa.String(length=512), nullable=True, comment='引用路径'),
    sa.Column('ref_version', sa.String(length=32), nullable=True, comment='引用版本'),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_no', sa.Float(), nullable=True),
    sa.Column('del_flag', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('ref_id'),
    comment='JSON Schema 模型引用关系表'
    )
    op.create_index('ix_schema_model_refs_model_id', 'schema_model_refs', ['model_id'], unique=False)
    op.create_index('ix_schema_model_refs_ref_model_id', 'schema_model_refs', ['ref_model_id'], unique=False)
    op.create_table('schema_model_usage',
    sa.Column('usage_id', sa.String(length=64), nullable=False, comment='使用关系ID'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型ID'),
    sa.Column('usage_type', sa.String(length=32), nullable=False, comment='使用类型'),
    sa.Column('usage_target_id', sa.String(length=64), nullable=False, comment='使用目标ID'),
    sa.Column('usage_target_name', sa.String(length=256), nullable=True, comment='使用目标名称'),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_no', sa.Float(), nullable=True),
    sa.Column('del_flag', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('usage_id'),
    comment='JSON Schema 模型使用关系表'
    )
    op.create_index('ix_schema_model_usage_model_id', 'schema_model_usage', ['model_id'], unique=False)
    op.create_index('ix_schema_model_usage_target', 'schema_model_usage', ['usage_type', 'usage_target_id'], unique=False)
    op.create_table('schema_model_versions',
    sa.Column('version_id', sa.String(length=64), nullable=False, comment='版本ID'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型ID'),
    sa.Column('version', sa.Integer(), nullable=False, comment='内部版本号'),
    sa.Column('revision', sa.String(length=32), nullable=True, comment='语义版本号'),
    sa.Column('schema_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Schema快照'),
    sa.Column('nodes_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='节点快照'),
    sa.Column('change_log', sa.Text(), nullable=True, comment='变更说明'),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_no', sa.Float(), nullable=True),
    sa.Column('del_flag', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('version_id'),
    comment='JSON Schema 模型版本表'
    )
    op.create_index('ix_schema_model_versions_model_id', 'schema_model_versions', ['model_id'], unique=False)
    op.create_index('ix_schema_model_versions_revision', 'schema_model_versions', ['revision'], unique=False)
    op.create_table('schema_models',
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('case_id', sa.Integer(), nullable=True, comment='关联的测试用例ID'),
    sa.Column('group_id', sa.String(length=64), nullable=True, comment='所属分组ID'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='模型唯一名称'),
    sa.Column('display_name', sa.String(length=128), nullable=True, comment='展示名称'),
    sa.Column('title', sa.String(length=256), nullable=True, comment='JSON Schema标题'),
    sa.Column('schema_draft', sa.String(length=32), nullable=True, comment='JSON Schema版本'),
    sa.Column('root_node_id', sa.String(length=64), nullable=True, comment='根节点ID'),
    sa.Column('model_category', sa.String(length=32), nullable=True, comment='模型分类：request/response/common/enum/dto'),
    sa.Column('model_role', sa.String(length=32), nullable=True, comment='模型角色：input/output/entity/enum'),
    sa.Column('parent_model_id', sa.String(length=64), nullable=True, comment='派生来源模型ID'),
    sa.Column('source_model_name', sa.String(length=128), nullable=True, comment='来源模型名称'),
    sa.Column('code_class_name', sa.String(length=128), nullable=True, comment='代码生成类名'),
    sa.Column('code_file_name', sa.String(length=256), nullable=True, comment='代码生成文件名'),
    sa.Column('source_table_name', sa.String(length=128), nullable=True, comment='来源数据库表名'),
    sa.Column('visibility', sa.String(length=32), nullable=False, comment='可见性：private/project/public'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态：draft/published/deprecated'),
    sa.Column('version', sa.Integer(), nullable=False, comment='内部版本号'),
    sa.Column('revision', sa.String(length=32), nullable=True, comment='语义版本号'),
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='来源类型：manual/json/openapi/database/code'),
    sa.Column('source_id', sa.String(length=128), nullable=True, comment='来源业务ID'),
    sa.Column('raw_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='原始JSON Schema'),
    sa.Column('raw_schema_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='模型级扩展Schema关键字'),
    sa.Column('generated_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='生成后的JSON Schema'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='标签'),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_no', sa.Float(), nullable=True),
    sa.Column('del_flag', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('model_id'),
    comment='JSON Schema 数据模型主表'
    )
    op.create_index('ix_schema_models_group_id', 'schema_models', ['group_id'], unique=False)
    op.create_index('ix_schema_models_name', 'schema_models', ['name'], unique=False)
    op.create_index('ix_schema_models_project_id', 'schema_models', ['project_id'], unique=False)
    op.create_index('ix_schema_models_status', 'schema_models', ['status'], unique=False)
    op.create_table('schema_nodes',
    sa.Column('node_id', sa.String(length=64), nullable=False, comment='节点ID'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='所属模型ID'),
    sa.Column('parent_id', sa.String(length=64), nullable=True, comment='父节点ID'),
    sa.Column('root_id', sa.String(length=64), nullable=True, comment='根节点ID'),
    sa.Column('node_kind', sa.String(length=32), nullable=False, comment='节点类型：root/property/items/composition/ref'),
    sa.Column('field_name', sa.String(length=128), nullable=True, comment='字段名'),
    sa.Column('display_name', sa.String(length=128), nullable=True, comment='展示名'),
    sa.Column('alias', sa.String(length=128), nullable=True, comment='字段映射名或代码生成别名'),
    sa.Column('source_field_name', sa.String(length=128), nullable=True, comment='来源字段名'),
    sa.Column('source_field_type', sa.String(length=128), nullable=True, comment='来源字段类型'),
    sa.Column('source_field_comment', sa.Text(), nullable=True, comment='来源字段注释'),
    sa.Column('code_field_name', sa.String(length=128), nullable=True, comment='代码生成字段名'),
    sa.Column('title', sa.String(length=256), nullable=True, comment='JSON Schema title'),
    sa.Column('type', sa.String(length=32), nullable=False, comment='JSON Schema主类型'),
    sa.Column('type_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='多类型列表'),
    sa.Column('nullable', sa.Boolean(), nullable=False, comment='是否允许NULL'),
    sa.Column('required', sa.Boolean(), nullable=False, comment='是否必填'),
    sa.Column('deprecated', sa.Boolean(), nullable=False, comment='是否废弃'),
    sa.Column('access_mode', sa.String(length=32), nullable=False, comment='读写行为'),
    sa.Column('format', sa.String(length=64), nullable=True, comment='format'),
    sa.Column('default_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='默认值'),
    sa.Column('example_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='示例值'),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='示例值列表'),
    sa.Column('enum_enabled', sa.Boolean(), nullable=False, comment='是否启用枚举'),
    sa.Column('enum_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='枚举值'),
    sa.Column('enum_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='枚举元数据'),
    sa.Column('const_enabled', sa.Boolean(), nullable=False, comment='是否启用常量'),
    sa.Column('const_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='常量值'),
    sa.Column('mock_enabled', sa.Boolean(), nullable=False, comment='是否启用Mock'),
    sa.Column('mock_type', sa.String(length=32), nullable=True, comment='Mock类型'),
    sa.Column('mock_rule', sa.String(length=256), nullable=True, comment='Mock规则'),
    sa.Column('mock_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='固定Mock值'),
    sa.Column('mock_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Mock配置'),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='类型约束'),
    sa.Column('composition', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='组合结构配置'),
    sa.Column('ref_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='引用配置'),
    sa.Column('xml_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='XML配置'),
    sa.Column('source', sa.String(length=32), nullable=True, comment='节点来源'),
    sa.Column('source_path', sa.String(length=1024), nullable=True, comment='来源路径'),
    sa.Column('import_hint', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='导入推断信息'),
    sa.Column('raw_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='当前节点原始Schema'),
    sa.Column('raw_schema_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='不支持可视化的Schema关键字'),
    sa.Column('ui_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='前端临时状态'),
    sa.Column('path', sa.String(length=1024), nullable=True, comment='字段路径'),
    sa.Column('json_pointer', sa.String(length=1024), nullable=True, comment='JSON Pointer'),
    sa.Column('level', sa.Integer(), nullable=False, comment='层级'),
    sa.Column('expanded', sa.Boolean(), nullable=True, comment='是否展开'),
    sa.Column('locked', sa.Boolean(), nullable=True, comment='是否锁定'),
    sa.Column('sort_no', sa.Float(), nullable=False, comment='排序号'),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('del_flag', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('node_id'),
    comment='JSON Schema 可视化节点表'
    )
    op.create_index('ix_schema_nodes_json_pointer', 'schema_nodes', ['json_pointer'], unique=False)
    op.create_index('ix_schema_nodes_model_id', 'schema_nodes', ['model_id'], unique=False)
    op.create_index('ix_schema_nodes_parent_id', 'schema_nodes', ['parent_id'], unique=False)
    op.create_index('ix_schema_nodes_path', 'schema_nodes', ['path'], unique=False)
    op.alter_column('module_demo_all_types', 'create_by',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'update_by',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'remark',
               existing_type=sa.VARCHAR(length=500),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'description',
               existing_type=sa.TEXT(),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'sort_no',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'del_flag',
               existing_type=sa.VARCHAR(length=1),
               comment='',
               existing_nullable=True)
    op.alter_column('module_uuid_demo', 'type',
               existing_type=postgresql.ENUM('normal', 'important', 'urgent', name='module_uuid_demo_type_enum'),
               nullable=False,
               existing_comment='业务类型')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_uuid_demo', 'type',
               existing_type=postgresql.ENUM('normal', 'important', 'urgent', name='module_uuid_demo_type_enum'),
               nullable=True,
               existing_comment='业务类型')
    op.alter_column('module_demo_all_types', 'del_flag',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'sort_no',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'remark',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'update_by',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'create_by',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_index('ix_schema_nodes_path', table_name='schema_nodes')
    op.drop_index('ix_schema_nodes_parent_id', table_name='schema_nodes')
    op.drop_index('ix_schema_nodes_model_id', table_name='schema_nodes')
    op.drop_index('ix_schema_nodes_json_pointer', table_name='schema_nodes')
    op.drop_table('schema_nodes')
    op.drop_index('ix_schema_models_status', table_name='schema_models')
    op.drop_index('ix_schema_models_project_id', table_name='schema_models')
    op.drop_index('ix_schema_models_name', table_name='schema_models')
    op.drop_index('ix_schema_models_group_id', table_name='schema_models')
    op.drop_table('schema_models')
    op.drop_index('ix_schema_model_versions_revision', table_name='schema_model_versions')
    op.drop_index('ix_schema_model_versions_model_id', table_name='schema_model_versions')
    op.drop_table('schema_model_versions')
    op.drop_index('ix_schema_model_usage_target', table_name='schema_model_usage')
    op.drop_index('ix_schema_model_usage_model_id', table_name='schema_model_usage')
    op.drop_table('schema_model_usage')
    op.drop_index('ix_schema_model_refs_ref_model_id', table_name='schema_model_refs')
    op.drop_index('ix_schema_model_refs_model_id', table_name='schema_model_refs')
    op.drop_table('schema_model_refs')
    # ### end Alembic commands ###
