"""测试生成枚举

Revision ID: ffa301fbd93e
Revises: 53f8c7000baf
Create Date: 2026-06-01 15:42:17.050818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa301fbd93e'
down_revision: Union[str, Sequence[str], None] = '53f8c7000baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TYPE "demo_status_enum" ADD VALUE IF NOT EXISTS \'TEST222\'')
    op.alter_column('module_demo_all_types', 'real_value',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_comment='单精度浮点-real',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'create_by',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'update_by',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'remark',
               existing_type=sa.VARCHAR(length=500),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'description',
               existing_type=sa.TEXT(),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'sort_no',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'del_flag',
               existing_type=sa.VARCHAR(length=1),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_demo_all_types', 'del_flag',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'sort_no',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'remark',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'update_by',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'create_by',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('module_demo_all_types', 'real_value',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_comment='单精度浮点-real',
               existing_nullable=True)
    op.execute('ALTER TYPE "demo_status_enum" RENAME TO "demo_status_enum_old"')
    op.execute('CREATE TYPE "demo_status_enum" AS ENUM (\'DRAFT\', \'ACTIVE\', \'DISABLED\', \'TEST\')')
    op.execute('ALTER TABLE "public"."module_demo_all_types" ALTER COLUMN "enum_value" TYPE "demo_status_enum" USING "enum_value"::text::"demo_status_enum"')
    op.execute('DROP TYPE "demo_status_enum_old"')
    # ### end Alembic commands ###
